fix: run tests in different jobs
Signed-off-by: matttrach <matt.trachier@suse.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,23 +21,7 @@ permissions:
   actions: read
 
 jobs:
-  clear-space:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0 https://github.com/actions/checkout
-        with:
-          fetch-depth: 0
-      - name: 'Clear out GitHub Runner'
-        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0 https://github.com/actions/github-script
-        with:
-          script: |
-            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/clear-runner.js`;
-            const { default: script } = await import(scriptPath);
-            await script({ core });
-
   release:
-    needs:
-      - clear-space
     runs-on: ubuntu-latest
     outputs:
       release_pr: ${{ steps.release-please.outputs.pr }}
@@ -71,16 +55,91 @@ jobs:
               core.setFailed(`Failed to create comment on release PR: ${error.message}`);
             }
 
+  # using a workflow artifact to share IP data between jobs
+  create-ip-list-artifact:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Create Empty IP List
+        run: |
+          install -d ip_data
+          touch ip_data/ip.txt
+          echo "List Initialized" > ip_data/ip.txt
+      - name: Upload IP List
+        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0 https://github.com/actions/upload-artifact
+        with:
+          name: ip-list
+          path: ip_data/ip.txt
+          overwrite: true
+
+  # this creates a loop using workflow logic,
+  #   each iteration of the loop is in its own job
+  #   this is important because we want each iteration to be a separate VM
+  #   we are trying to get a clean filesystem and different IP for each test
   test:
     needs:
-      - clear-space
       - release
+      - create-ip-list-artifact
     if: needs.release.outputs.release_pr
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        test_name:
+          - TestOneBasic
+          - TestThreeBasic
+          - TestProductionBasic
+        attempts: [1,2,3]
     steps:
       - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0 https://github.com/actions/checkout
         with:
           fetch-depth: 0
+      - name: 'Clear out GitHub Runner'
+        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0 https://github.com/actions/github-script
+        with:
+          script: |
+            # requires checkout before step
+            # each job runs in its own ephemeral VM, so each job needs its own clear out step
+            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/clear-runner.js`;
+            const { default: script } = await import(scriptPath);
+            await script({ core });
+      - name: Add jitter
+        run: |
+          # this jitter aligns the tests so that they don't all start at the same time
+          # the first test to run should have time to upload its IP information before the second one in line
+          JOB_INDEX=${{ strategy.job-index }}
+          DELAY=$(( JOB_INDEX * 45 )) # adjust this to the time it takes to upload the IP information
+          sleep $DELAY
+      - name: Download IP List
+        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0 https://github.com/actions/download-artifact/releases
+        with:
+          name: ip-list
+          path: ip_data/ip.txt
+      - name: Check for Unique IP
+        id: get_ip
+        run: |
+          IP_DATA_FILE="ip_data/ip.txt"
+          if [ ! -f "$IP_DATA_FILE" ]; then echo "failed to find IP list..."; exit 1; fi
+          echo "IP list: "
+          cat $IP_DATA_FILE
+
+          CURRENT_IP="$(curl -s https://ipinfo.io/ip)"
+
+          if ! grep -q "$CURRENT_IP" "$IP_DATA_FILE"; then
+            echo "$CURRENT_IP is not in IP list..."
+            echo "$CURRENT_IP" >> "$IP_DATA_FILE"
+          else
+            echo "$CURRENT_IP is already in IP list, failing..."
+            exit 1
+          fi
+      - name: Upload IP List for next Job
+        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0 https://github.com/actions/upload-artifact
+        with:
+          name: ip-list
+          path: ip_data/ip.txt
+          overwrite: true
+      - name: Ready
+        run: |
+          IP=$(curl -s https://ifconfig.me)
+          echo "Running ${{ matrix.test_name }} from IP: $IP"
       - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0 https://github.com/actions/setup-go
         with:
           go-version-file: 'go.mod'
@@ -101,7 +160,7 @@ jobs:
           role-to-assume: ${{env.AWS_ROLE}}
           role-session-name: ${{github.run_id}}
           aws-region: ${{env.AWS_REGION}}
-          role-duration-seconds: 28800 # 8 hours
+          role-duration-seconds: 21600 # 6 hours is the maximum GitHub execution time
           output-credentials: true
       - name: run_tests
         shell: '/home/runner/.nix-profile/bin/nix develop --ignore-environment --extra-experimental-features nix-command --extra-experimental-features flakes --keep HOME --keep SSH_AUTH_SOCK --keep IDENTIFIER --keep GITHUB_TOKEN --keep GITHUB_OWNER --keep ZONE --keep AWS_ROLE --keep AWS_REGION --keep AWS_DEFAULT_REGION --keep AWS_ACCESS_KEY_ID --keep AWS_SECRET_ACCESS_KEY --keep AWS_SESSION_TOKEN --keep UPDATECLI_GPGTOKEN --keep UPDATECLI_GITHUB_TOKEN --keep UPDATECLI_GITHUB_ACTOR --keep GPG_SIGNING_KEY --keep NIX_SSL_CERT_FILE --keep NIX_ENV_LOADED --keep TERM --command bash -e {0}'
@@ -109,20 +168,19 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ steps.aws-creds.outputs.aws-access-key-id }}
           AWS_SECRET_ACCESS_KEY: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
           AWS_SESSION_TOKEN: ${{ steps.aws-creds.outputs.aws-session-token }}
-          AWS_MAX_ATTEMPTS: 100
-          AWS_RETRY_MODE: adaptive
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           GITHUB_OWNER: rancher
           IDENTIFIER: ${{github.run_id}}
           ZONE: ${{secrets.ZONE}}
-          ACME_SERVER_URL: https://acme-v02.api.letsencrypt.org/directory
-          RANCHER_INSECURE: false
         run: |
-          ./run_tests.sh -s
+          export AWS_MAX_ATTEMPTS="100"
+          export AWS_RETRY_MODE="adaptive"
+          export ACME_SERVER_URL="https://acme-v02.api.letsencrypt.org/directory"
+          export RANCHER_INSECURE="false"
+          ./run_tests.sh -t ${{matrix.test_name}}
 
   cleanup:
     needs:
-      - clear-space
       - release
       - test
     if: always() && needs.release.outputs.release_pr
@@ -132,6 +190,15 @@ jobs:
         with:
           token: ${{secrets.GITHUB_TOKEN}}
           fetch-depth: 0
+      - name: 'Clear out GitHub Runner'
+        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0 https://github.com/actions/github-script
+        with:
+          script: |
+            # requires checkout before step
+            # each job runs in its own ephemeral VM, so each job needs its own clear out step
+            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/clear-runner.js`;
+            const { default: script } = await import(scriptPath);
+            await script({ core });
       - id: aws-creds
         uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0 https://github.com/aws-actions/configure-aws-credentials/tags
         with:
@@ -152,14 +219,13 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ steps.aws-creds.outputs.aws-access-key-id }}
           AWS_SECRET_ACCESS_KEY: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
           AWS_SESSION_TOKEN: ${{ steps.aws-creds.outputs.aws-session-token }}
-          AWS_MAX_ATTEMPTS: 100
           IDENTIFIER: ${{github.run_id}}
         run: |
+          export AWS_MAX_ATTEMPTS="100"
           ./run_tests.sh -c $IDENTIFIER
 
   report:
     needs:
-      - clear-space
       - release
       - test
       - cleanup
@@ -199,7 +265,6 @@ jobs:
 
   rc-release:
     needs:
-      - clear-space
       - release
       - test
       - cleanup
@@ -295,7 +360,6 @@ jobs:
   # This runs after release-please generates a release, so when the release PR is merged
   publish:
     needs:
-      - clear-space
       - release
       - test
       - cleanup
